# Local preview playbook for domus-nvim docs
# For production, this component is aggregated via domus-docs

site:
  title: Domus Neovim
  start_page: nvim::index.adoc

content:
  sources:
    - url: ..
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./build/site
